// systems.js — the curated per-country library-systems lists for onboarding
// autocomplete. Data files are generated by scripts/refresh-systems.mjs.

import { country } from './countries.js';

const cache = {};   // country code -> systems array

// Load a country's systems list once (lazily; default US). Returns [] if the
// file is unavailable, so the manual-entry fallback still works offline.
export async function loadSystems(countryCode) {
  const c = country(countryCode);
  if (cache[c.code]) return cache[c.code];
  try {
    const res = await fetch('./' + c.systemsFile);
    if (!res.ok) throw new Error('HTTP ' + res.status);
    const json = await res.json();
    cache[c.code] = json.systems || [];
  } catch (e) {
    console.warn(`Could not load ${c.code} library systems list:`, e);
    cache[c.code] = [];
  }
  return cache[c.code];
}

// Rank systems for a query. Prioritises prefix matches, then word-boundary
// matches, then substring; ties broken by library count (bigger systems first).
export function searchSystems(systems, query, limit = 8) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const scored = [];
  for (const s of systems) {
    const name = s.name.toLowerCase();
    let score;
    if (name.startsWith(q)) score = 0;
    else if (new RegExp('\\b' + escapeRe(q)).test(name)) score = 1;
    else if (name.includes(q)) score = 2;
    else if (s.value.toLowerCase() === q) score = 0; // exact Q-id / operator value
    else continue;
    scored.push({ s, score });
  }
  scored.sort((a, b) => a.score - b.score || (b.s.count - a.s.count) || a.s.name.localeCompare(b.s.name));
  return scored.slice(0, limit).map(x => x.s);
}

function escapeRe(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }
